name: Build V Project (Windows EXE)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install V
        run: |
          git clone https://github.com/vlang/v
          cd v
          .\make.bat
          echo "::add-path::$PWD"

      - name: Build V project from src folder
        run: |
          v -os windows -o v-hill.exe src

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: v-hill
          path: v-hill.exe
